# Generated by Django 5.2.7 on 2025-12-16 07:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sertifikat nomi')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Tashkilot')),
                ('issue_date', models.DateField(verbose_name='Berilgan sana')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Muddati')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='Sertifikat ID')),
                ('credential_url', models.URLField(blank=True, verbose_name='Sertifikat linki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifikat rasmi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('map_embed_code', models.TextField(help_text='Google Maps embed kodi', verbose_name='Xarita kodi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Kontakt Ma'lumot",
                'verbose_name_plural': "Kontakt Ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('read', "O'qilgan"), ('replied', 'Javob berilgan'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Kontakt Xabari',
                'verbose_name_plural': 'Kontakt Xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Sertifikat')], max_length=20, verbose_name='Daraja')),
                ('field_of_study', models.CharField(max_length=200, verbose_name="Yo'nalish")),
                ('institution', models.CharField(max_length=200, verbose_name="Ta'lim muassasi")),
                ('start_year', models.IntegerField(verbose_name='Boshlanish yili')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='Tugash yili')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_current', models.BooleanField(default=False, verbose_name="Joriy ta'lim")),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Ta'lim",
                'verbose_name_plural': "Ta'lim",
                'ordering': ['order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('work', 'Ish Tajribasi'), ('education', "Ta'lim"), ('summary', "Qisqacha ma'lumot"), ('certificate', 'Sertifikatlar')], max_length=20, verbose_name='Tajriba turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name="Kompaniya/Ta'lim muassasi")),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('current', models.BooleanField(default=False, verbose_name='Hozirgi ish')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Tajriba',
                'verbose_name_plural': 'Tajribalar',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('filter_name', models.CharField(help_text='Isotope filter uchun class nomi', max_length=50, verbose_name='Filter nomi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Portfolio Kategoriya',
                'verbose_name_plural': 'Portfolio Kategoriyalari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('title', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('short_bio', models.CharField(blank=True, max_length=255, null=True, verbose_name="Qisqacha ma'lumot")),
                ('detailed_bio', models.TextField(verbose_name="Batafsil ma'lumot")),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profil rasmi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('website', models.URLField(blank=True, verbose_name='Veb sayt')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Daraja')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Yosh')),
                ('freelance_available', models.BooleanField(default=True, verbose_name='Freelance mavjud')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='CV fayli')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram Link')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram Link')),
                ('github', models.URLField(blank=True, verbose_name='GitHub Link')),
                ('gmail', models.EmailField(blank=True, max_length=254, verbose_name='Gmail')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('leetcode', models.URLField(blank=True, null=True)),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Hero fon rasm')),
                ('hero_title', models.CharField(blank=True, max_length=100, verbose_name='Hero sarlavha')),
                ('hero_subtitles', models.TextField(help_text="Herotda ko'rinadigan kasblar. Har birini vergul bilan ajrating", verbose_name='Hero kasblar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('project_type', models.CharField(choices=[('personal', 'Shaxsiy loyiha'), ('client', 'Mijoz loyihasi'), ('open_source', 'Ochiq manba')], default='personal', max_length=20, verbose_name='Loyiha turi')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Mijoz nomi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('technologies', models.TextField(help_text='Foydalanilgan texnologiyalar (vergul bilan ajratilgan)', verbose_name='Texnologiyalar')),
                ('github_link', models.URLField(blank=True, verbose_name='GitHub Link')),
                ('live_link', models.URLField(blank=True, verbose_name='Live Link')),
                ('featured_image', models.ImageField(upload_to='projects/', verbose_name='Asosiy rasm')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Bootstrap icon class. Masalan: bi bi-briefcase', max_length=50, verbose_name='Icon class')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill nomi')),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Foiz')),
                ('category', models.CharField(choices=[('technical', 'Texnik'), ('soft', 'Soft Skill'), ('language', 'Tillar'), ('framework', 'Frameworklar')], default='technical', max_length=50, verbose_name='Kategoriya')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skilllar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('skype', 'Skype'), ('discord', 'Discord'), ('medium', 'Medium'), ('stackoverflow', 'Stack Overflow'), ('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit')], max_length=20, verbose_name='Platforma')),
                ('url', models.URLField(verbose_name='Link')),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class. Masalan: bi bi-github', max_length=50, verbose_name='Icon class')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Ijtimoiy Tarmoq',
                'verbose_name_plural': 'Ijtimoiy Tarmoqlar',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('company', models.CharField(max_length=200, verbose_name='Kompaniya')),
                ('content', models.TextField(verbose_name='Fikr')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Rasm')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Fikr-Mulohaza',
                'verbose_name_plural': 'Fikr-Mulohazalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('short_description', models.CharField(max_length=200, verbose_name='Qisqacha tavsif')),
                ('detailed_description', models.TextField(blank=True, verbose_name='Batafsil tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Rasm')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('github_link', models.URLField(blank=True, verbose_name='GitHub Repository Link')),
                ('live_demo_link', models.URLField(blank=True, verbose_name='Live Demo Link')),
                ('technologies_used', models.CharField(blank=True, help_text='Foydalanilgan texnologiyalar (vergul bilan ajratilgan)', max_length=300, verbose_name='Foydalanilgan texnologiyalar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configapp.portfoliocategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Portfolio Loyiha',
                'verbose_name_plural': 'Portfolio Loyihalari',
                'ordering': ['order', '-date_created'],
            },
        ),
    ]
