# Generated by Django 6.0 on 2025-12-15 08:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sertifikat nomi')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Tashkilot')),
                ('issue_date', models.DateField(verbose_name='Berilgan sana')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Muddati')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='Sertifikat ID')),
                ('credential_url', models.URLField(blank=True, verbose_name='Sertifikat linki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifikat rasmi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Sertifikat')], max_length=20, verbose_name='Daraja')),
                ('field_of_study', models.CharField(max_length=200, verbose_name="Yo'nalish")),
                ('institution', models.CharField(max_length=200, verbose_name="Ta'lim muassasi")),
                ('start_year', models.IntegerField(verbose_name='Boshlanish yili')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='Tugash yili')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_current', models.BooleanField(default=False, verbose_name="Joriy ta'lim")),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Ta'lim",
                'verbose_name_plural': "Ta'lim",
                'ordering': ['order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('project_type', models.CharField(choices=[('personal', 'Shaxsiy loyiha'), ('client', 'Mijoz loyihasi'), ('open_source', 'Ochiq manba')], default='personal', max_length=20, verbose_name='Loyiha turi')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Mijoz nomi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('technologies', models.TextField(help_text='Foydalanilgan texnologiyalar (vergul bilan ajratilgan)', verbose_name='Texnologiyalar')),
                ('github_link', models.URLField(blank=True, verbose_name='GitHub Link')),
                ('live_link', models.URLField(blank=True, verbose_name='Live Link')),
                ('featured_image', models.ImageField(upload_to='projects/', verbose_name='Asosiy rasm')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('skype', 'Skype'), ('stackoverflow', 'Stack Overflow'), ('medium', 'Medium'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('codepen', 'CodePen'), ('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank')], max_length=20, verbose_name='Platforma')),
                ('url', models.URLField(verbose_name='Link')),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class. Masalan: bi bi-github', max_length=50, verbose_name='Icon class')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Ijtimoiy Tarmoq',
                'verbose_name_plural': 'Ijtimoiy Tarmoqlar',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('company', models.CharField(max_length=200, verbose_name='Kompaniya')),
                ('content', models.TextField(verbose_name='Fikr')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Rasm')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Fikr-Mulohaza',
                'verbose_name_plural': 'Fikr-Mulohazalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': "Kontakt Ma'lumot", 'verbose_name_plural': "Kontakt Ma'lumotlari"},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kontakt Xabari', 'verbose_name_plural': 'Kontakt Xabarlari'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-start_date'], 'verbose_name': 'Tajriba', 'verbose_name_plural': 'Tajribalar'},
        ),
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Portfolio Kategoriya', 'verbose_name_plural': 'Portfolio Kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', '-date_created'], 'verbose_name': 'Portfolio Loyiha', 'verbose_name_plural': 'Portfolio Loyihalari'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profil'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skilllar'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('read', "O'qilgan"), ('replied', 'Javob berilgan'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram Link'),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='map_embed_code',
            field=models.TextField(help_text='Google Maps embed kodi', verbose_name='Xarita kodi'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name="O'qilgan"),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name="Kompaniya/Ta'lim muassasi"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Hozirgi ish'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('work', 'Ish Tajribasi'), ('education', "Ta'lim"), ('summary', "Qisqacha ma'lumot"), ('certificate', 'Sertifikatlar')], max_length=20, verbose_name='Tajriba turi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartibi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='filter_name',
            field=models.CharField(help_text='Isotope filter uchun class nomi', max_length=50, verbose_name='Filter nomi'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartibi'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configapp.portfoliocategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='detailed_description',
            field=models.TextField(blank=True, verbose_name='Batafsil tavsif'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tavsiya etilgan'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartibi'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='short_description',
            field=models.CharField(max_length=200, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='technologies_used',
            field=models.CharField(blank=True, help_text='Foydalanilgan texnologiyalar (vergul bilan ajratilgan)', max_length=300, verbose_name='Foydalanilgan texnologiyalar'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yosh'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='detailed_bio',
            field=models.TextField(verbose_name="Batafsil ma'lumot"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='freelance_available',
            field=models.BooleanField(default=True, verbose_name='Freelance mavjud'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub Link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Gmail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_background',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Hero fon rasm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_subtitles',
            field=models.TextField(help_text="Herotda ko'rinadigan kasblar. Har birini vergul bilan ajrating", verbose_name='Hero kasblar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hero sarlavha'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='leetcode',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profil rasmi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='CV fayli'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Qisqacha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Veb sayt'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(help_text='Bootstrap icon class. Masalan: bi bi-briefcase', max_length=50, verbose_name='Icon class'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartibi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Texnik'), ('soft', 'Soft Skill'), ('language', 'Tillar'), ('framework', 'Frameworklar')], default='technical', max_length=50, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Skill nomi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartibi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Foiz'),
        ),
    ]
